# Generated by Django 5.2.6 on 2025-09-20 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('team', models.CharField(default='Unknown', max_length=50)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('QB', 'Quarterback'), ('WR1', 'Wide Receiver 1'), ('WR2', 'Wide Receiver 2'), ('RB1', 'Running Back 1'), ('RB2', 'Running Back 2'), ('TE', 'Tight End'), ('FLEX', 'Flex'), ('K', 'Kicker'), ('DEF', 'Defense'), ('BENCH1', 'Bench 1'), ('BENCH2', 'Bench 2'), ('BENCH3', 'Bench 3'), ('BENCH4', 'Bench 4'), ('BENCH5', 'Bench 5'), ('BENCH6', 'Bench 6')], max_length=10)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='main_app.team')),
            ],
        ),
    ]
