# Generated by Django 5.2.6 on 2025-09-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
