# Generated by Django 5.2.6 on 2025-09-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rosterspot_team_rosterspot_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
