# Generated by Django 5.2.6 on 2025-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_player_number_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team', 'position')},
        ),
    ]
