# Generated by Django 5.2.6 on 2025-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='main_app.RosterSpot', to='main_app.player'),
        ),
    ]
