# Generated by Django 5.2.6 on 2025-09-19 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rosterspot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='nfl_team',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rosterspot',
            name='slot',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('WR1', 'Wide Receiver 1'), ('WR2', 'Wide Receiver 2'), ('RB1', 'Running Back 1'), ('RB2', 'Running Back 2'), ('TE', 'Tight End'), ('FLEX', 'Flex'), ('K', 'Kicker'), ('DEF', 'Defense'), ('BENCH1', 'Bench 1'), ('BENCH2', 'Bench 2'), ('BENCH3', 'Bench 3'), ('BENCH4', 'Bench 4'), ('BENCH5', 'Bench 5'), ('BENCH6', 'Bench 6')], default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.player'),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='main_app.team'),
        ),
    ]
