# Generated by Django 5.2.6 on 2025-09-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_player_age_remove_player_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
